global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ms-metrics-with-grafana'
    metrics_path: /ms-metrics-with-grafana/actuator/prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ['172.17.0.1:8081'] #If running on linux use ip addr docker0. Else host.docker.internal for windows